// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"apu/pkg/store/mysql/model"
)

func newDocument(db *gorm.DB, opts ...gen.DOOption) document {
	_document := document{}

	_document.documentDo.UseDB(db, opts...)
	_document.documentDo.UseModel(&model.Document{})

	tableName := _document.documentDo.TableName()
	_document.ALL = field.NewAsterisk(tableName)
	_document.ID = field.NewInt64(tableName, "id")
	_document.Stage = field.NewInt32(tableName, "stage")
	_document.Source = field.NewInt32(tableName, "source")
	_document.Key = field.NewUint64(tableName, "key")
	_document.Author = field.NewString(tableName, "author")
	_document.PublishTime = field.NewTime(tableName, "publish_time")
	_document.ReadNum = field.NewInt32(tableName, "read_num")
	_document.LikeNum = field.NewInt32(tableName, "like_num")
	_document.CollectNum = field.NewInt32(tableName, "collect_num")
	_document.OriginalURL = field.NewString(tableName, "original_url")
	_document.Title = field.NewString(tableName, "title")
	_document.Content = field.NewString(tableName, "content")
	_document.CreateTime = field.NewTime(tableName, "create_time")
	_document.UpdateTime = field.NewTime(tableName, "update_time")

	_document.fillFieldMap()

	return _document
}

type document struct {
	documentDo

	ALL         field.Asterisk
	ID          field.Int64
	Stage       field.Int32
	Source      field.Int32
	Key         field.Uint64
	Author      field.String
	PublishTime field.Time
	ReadNum     field.Int32
	LikeNum     field.Int32
	CollectNum  field.Int32
	OriginalURL field.String
	Title       field.String
	Content     field.String
	CreateTime  field.Time
	UpdateTime  field.Time

	fieldMap map[string]field.Expr
}

func (d document) Table(newTableName string) *document {
	d.documentDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d document) As(alias string) *document {
	d.documentDo.DO = *(d.documentDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *document) updateTableName(table string) *document {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.Stage = field.NewInt32(table, "stage")
	d.Source = field.NewInt32(table, "source")
	d.Key = field.NewUint64(table, "key")
	d.Author = field.NewString(table, "author")
	d.PublishTime = field.NewTime(table, "publish_time")
	d.ReadNum = field.NewInt32(table, "read_num")
	d.LikeNum = field.NewInt32(table, "like_num")
	d.CollectNum = field.NewInt32(table, "collect_num")
	d.OriginalURL = field.NewString(table, "original_url")
	d.Title = field.NewString(table, "title")
	d.Content = field.NewString(table, "content")
	d.CreateTime = field.NewTime(table, "create_time")
	d.UpdateTime = field.NewTime(table, "update_time")

	d.fillFieldMap()

	return d
}

func (d *document) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *document) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 14)
	d.fieldMap["id"] = d.ID
	d.fieldMap["stage"] = d.Stage
	d.fieldMap["source"] = d.Source
	d.fieldMap["key"] = d.Key
	d.fieldMap["author"] = d.Author
	d.fieldMap["publish_time"] = d.PublishTime
	d.fieldMap["read_num"] = d.ReadNum
	d.fieldMap["like_num"] = d.LikeNum
	d.fieldMap["collect_num"] = d.CollectNum
	d.fieldMap["original_url"] = d.OriginalURL
	d.fieldMap["title"] = d.Title
	d.fieldMap["content"] = d.Content
	d.fieldMap["create_time"] = d.CreateTime
	d.fieldMap["update_time"] = d.UpdateTime
}

func (d document) clone(db *gorm.DB) document {
	d.documentDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d document) replaceDB(db *gorm.DB) document {
	d.documentDo.ReplaceDB(db)
	return d
}

type documentDo struct{ gen.DO }

type IDocumentDo interface {
	gen.SubQuery
	Debug() IDocumentDo
	WithContext(ctx context.Context) IDocumentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDocumentDo
	WriteDB() IDocumentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDocumentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDocumentDo
	Not(conds ...gen.Condition) IDocumentDo
	Or(conds ...gen.Condition) IDocumentDo
	Select(conds ...field.Expr) IDocumentDo
	Where(conds ...gen.Condition) IDocumentDo
	Order(conds ...field.Expr) IDocumentDo
	Distinct(cols ...field.Expr) IDocumentDo
	Omit(cols ...field.Expr) IDocumentDo
	Join(table schema.Tabler, on ...field.Expr) IDocumentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDocumentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDocumentDo
	Group(cols ...field.Expr) IDocumentDo
	Having(conds ...gen.Condition) IDocumentDo
	Limit(limit int) IDocumentDo
	Offset(offset int) IDocumentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDocumentDo
	Unscoped() IDocumentDo
	Create(values ...*model.Document) error
	CreateInBatches(values []*model.Document, batchSize int) error
	Save(values ...*model.Document) error
	First() (*model.Document, error)
	Take() (*model.Document, error)
	Last() (*model.Document, error)
	Find() ([]*model.Document, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Document, err error)
	FindInBatches(result *[]*model.Document, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Document) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDocumentDo
	Assign(attrs ...field.AssignExpr) IDocumentDo
	Joins(fields ...field.RelationField) IDocumentDo
	Preload(fields ...field.RelationField) IDocumentDo
	FirstOrInit() (*model.Document, error)
	FirstOrCreate() (*model.Document, error)
	FindByPage(offset int, limit int) (result []*model.Document, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDocumentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d documentDo) Debug() IDocumentDo {
	return d.withDO(d.DO.Debug())
}

func (d documentDo) WithContext(ctx context.Context) IDocumentDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d documentDo) ReadDB() IDocumentDo {
	return d.Clauses(dbresolver.Read)
}

func (d documentDo) WriteDB() IDocumentDo {
	return d.Clauses(dbresolver.Write)
}

func (d documentDo) Session(config *gorm.Session) IDocumentDo {
	return d.withDO(d.DO.Session(config))
}

func (d documentDo) Clauses(conds ...clause.Expression) IDocumentDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d documentDo) Returning(value interface{}, columns ...string) IDocumentDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d documentDo) Not(conds ...gen.Condition) IDocumentDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d documentDo) Or(conds ...gen.Condition) IDocumentDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d documentDo) Select(conds ...field.Expr) IDocumentDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d documentDo) Where(conds ...gen.Condition) IDocumentDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d documentDo) Order(conds ...field.Expr) IDocumentDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d documentDo) Distinct(cols ...field.Expr) IDocumentDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d documentDo) Omit(cols ...field.Expr) IDocumentDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d documentDo) Join(table schema.Tabler, on ...field.Expr) IDocumentDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d documentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDocumentDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d documentDo) RightJoin(table schema.Tabler, on ...field.Expr) IDocumentDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d documentDo) Group(cols ...field.Expr) IDocumentDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d documentDo) Having(conds ...gen.Condition) IDocumentDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d documentDo) Limit(limit int) IDocumentDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d documentDo) Offset(offset int) IDocumentDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d documentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDocumentDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d documentDo) Unscoped() IDocumentDo {
	return d.withDO(d.DO.Unscoped())
}

func (d documentDo) Create(values ...*model.Document) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d documentDo) CreateInBatches(values []*model.Document, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d documentDo) Save(values ...*model.Document) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d documentDo) First() (*model.Document, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Document), nil
	}
}

func (d documentDo) Take() (*model.Document, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Document), nil
	}
}

func (d documentDo) Last() (*model.Document, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Document), nil
	}
}

func (d documentDo) Find() ([]*model.Document, error) {
	result, err := d.DO.Find()
	return result.([]*model.Document), err
}

func (d documentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Document, err error) {
	buf := make([]*model.Document, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d documentDo) FindInBatches(result *[]*model.Document, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d documentDo) Attrs(attrs ...field.AssignExpr) IDocumentDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d documentDo) Assign(attrs ...field.AssignExpr) IDocumentDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d documentDo) Joins(fields ...field.RelationField) IDocumentDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d documentDo) Preload(fields ...field.RelationField) IDocumentDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d documentDo) FirstOrInit() (*model.Document, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Document), nil
	}
}

func (d documentDo) FirstOrCreate() (*model.Document, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Document), nil
	}
}

func (d documentDo) FindByPage(offset int, limit int) (result []*model.Document, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d documentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d documentDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d documentDo) Delete(models ...*model.Document) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *documentDo) withDO(do gen.Dao) *documentDo {
	d.DO = *do.(*gen.DO)
	return d
}
