// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuthor = "author"

// Author mapped from table <author>
type Author struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Source     int32     `gorm:"column:source;not null" json:"source"`
	Nickname   string    `gorm:"column:nickname;not null" json:"nickname"`
	Avatar     string    `gorm:"column:avatar;not null" json:"avatar"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName Author's table name
func (*Author) TableName() string {
	return TableNameAuthor
}
