// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDocument = "document"

// Document mapped from table <document>
type Document struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Stage       int32     `gorm:"column:stage" json:"stage"`
	Source      int32     `gorm:"column:source;not null" json:"source"`
	Key         uint64    `gorm:"column:key;not null" json:"key"`
	Author      string    `gorm:"column:author;not null" json:"author"`
	PublishTime time.Time `gorm:"column:publish_time;not null" json:"publish_time"`
	ReadNum     int32     `gorm:"column:read_num;not null" json:"read_num"`
	LikeNum     int32     `gorm:"column:like_num;not null" json:"like_num"`
	CollectNum  int32     `gorm:"column:collect_num;not null" json:"collect_num"`
	OriginalURL string    `gorm:"column:original_url;not null" json:"original_url"`
	Title       string    `gorm:"column:title;not null" json:"title"`
	Content     string    `gorm:"column:content;not null" json:"content"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Document's table name
func (*Document) TableName() string {
	return TableNameDocument
}
