// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImage = "image"

// Image mapped from table <image>
type Image struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DocID       int64     `gorm:"column:doc_id;not null" json:"doc_id"`
	Source      int32     `gorm:"column:source;not null" json:"source"`
	Key         uint64    `gorm:"column:key;not null;comment:xxhash3(key)" json:"key"` // xxhash3(key)
	OriginalURL string    `gorm:"column:original_url;not null" json:"original_url"`
	Width       int32     `gorm:"column:width;not null" json:"width"`
	Height      int32     `gorm:"column:height;not null" json:"height"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Image's table name
func (*Image) TableName() string {
	return TableNameImage
}
