// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInteraction = "interaction"

// Interaction mapped from table <interaction>
type Interaction struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DocID       int64     `gorm:"column:doc_id;not null" json:"doc_id"`
	Day         int32     `gorm:"column:day;not null" json:"day"`
	ReadNum     int32     `gorm:"column:read_num;not null" json:"read_num"`
	LikeNum     int32     `gorm:"column:like_num;not null" json:"like_num"`
	CollectNum  int32     `gorm:"column:collect_num;not null" json:"collect_num"`
	DownloadNum int32     `gorm:"column:download_num;not null" json:"download_num"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName Interaction's table name
func (*Interaction) TableName() string {
	return TableNameInteraction
}
