// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNote = "note"

// Note mapped from table <note>
type Note struct {
	ID             int64     `gorm:"column:id;primaryKey" json:"id"`
	UID            uint64    `gorm:"column:uid;not null" json:"uid"`
	Source         int32     `gorm:"column:source;not null" json:"source"`
	State          int32     `gorm:"column:state;not null" json:"state"`
	Type           string    `gorm:"column:type;not null" json:"type"`
	PublishTime    time.Time `gorm:"column:publish_time;not null" json:"publish_time"`
	Title          string    `gorm:"column:title;not null" json:"title"`
	ReadCount      int32     `gorm:"column:read_count;not null" json:"read_count"`
	LikedCount     int32     `gorm:"column:liked_count;not null" json:"liked_count"`
	CollectedCount int32     `gorm:"column:collected_count;not null" json:"collected_count"`
	CommentCount   int32     `gorm:"column:comment_count;not null" json:"comment_count"`
	ShareCount     int32     `gorm:"column:share_count;not null" json:"share_count"`
	Content        string    `gorm:"column:content;not null" json:"content"`
	AuthorID       int64     `gorm:"column:author_id;not null" json:"author_id"`
	OriginalURL    string    `gorm:"column:original_url;not null" json:"original_url"`
	CreateTime     time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime     time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Note's table name
func (*Note) TableName() string {
	return TableNameNote
}
