// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNote = "note"

// Note mapped from table <note>
type Note struct {
	ID             uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Slug           string    `gorm:"column:slug;not null" json:"slug"`
	Source         int       `gorm:"column:source;not null" json:"source"`
	AuthorID       int64     `gorm:"column:author_id;not null" json:"author_id"`
	State          int       `gorm:"column:state;not null" json:"state"`
	Type           string    `gorm:"column:type;not null" json:"type"`
	PublishTime    time.Time `gorm:"column:publish_time;not null" json:"publish_time"`
	Title          string    `gorm:"column:title;not null" json:"title"`
	Description    string    `gorm:"column:description;not null;comment:由AI生成，如豆包" json:"description"` // 由AI生成，如豆包
	OriginalURL    string    `gorm:"column:original_url;not null" json:"original_url"`
	ReadCount      int       `gorm:"column:read_count;not null" json:"read_count"`
	LikedCount     int       `gorm:"column:liked_count;not null" json:"liked_count"`
	CollectedCount int       `gorm:"column:collected_count;not null" json:"collected_count"`
	CommentCount   int       `gorm:"column:comment_count;not null" json:"comment_count"`
	ShareCount     int       `gorm:"column:share_count;not null" json:"share_count"`
	CreateTime     time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime     time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Note's table name
func (*Note) TableName() string {
	return TableNameNote
}
