// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNoteTag = "note_tag"

// NoteTag mapped from table <note_tag>
type NoteTag struct {
	ID     int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NoteID int64 `gorm:"column:note_id;not null" json:"note_id"`
	TagID  int64 `gorm:"column:tag_id;not null" json:"tag_id"`
	Sort   int   `gorm:"column:sort;not null" json:"sort"`
}

// TableName NoteTag's table name
func (*NoteTag) TableName() string {
	return TableNameNoteTag
}
