// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWechatHeader = "wechat_headers"

// WechatHeader mapped from table <wechat_headers>
type WechatHeader struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Wxuin      string    `gorm:"column:wxuin;not null" json:"wxuin"`
	Type       string    `gorm:"column:type;not null" json:"type"`
	Headers    string    `gorm:"column:headers;not null" json:"headers"`
	Cookie     string    `gorm:"column:cookie;not null" json:"cookie"`
	Status     string    `gorm:"column:status;not null" json:"status"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName WechatHeader's table name
func (*WechatHeader) TableName() string {
	return TableNameWechatHeader
}
