// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWechatCookie = "wechat_cookie"

// WechatCookie mapped from table <wechat_cookie>
type WechatCookie struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Wxuin      string    `gorm:"column:wxuin;not null" json:"wxuin"`
	Type       string    `gorm:"column:type;not null" json:"type"`
	Cookie     string    `gorm:"column:cookie;not null" json:"cookie"`
	Status     string    `gorm:"column:status;not null" json:"status"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName WechatCookie's table name
func (*WechatCookie) TableName() string {
	return TableNameWechatCookie
}
