// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	// 批量创建笔记，重复仅更新时间以标记
	CreateNotes(ctx context.Context, arg []CreateNotesParams) *CreateNotesBatchResults
	GetNote(ctx context.Context, id int64) (Note, error)
	ListImagesByNoteID(ctx context.Context, noteID int64) ([]Image, error)
}

var _ Querier = (*Queries)(nil)
