// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"apu/kitex_gen/payment"
	payment2 "apu/payment"
	"apu/payment/mysql"
)

// Injectors from wire.go:

func initHandler() payment.PaymentSvc {
	client := mysql.NewEntClient()
	repository := mysql.NewRepository(client)
	paymentSvc := payment2.NewService(repository)
	return paymentSvc
}
