// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ParentID   int64     `gorm:"column:parent_id;not null" json:"parent_id"`
	Name       string    `gorm:"column:name;not null" json:"name"`
	Sort       int       `gorm:"column:sort;not null" json:"sort"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
