// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNoteImage = "note_image"

// NoteImage mapped from table <note_image>
type NoteImage struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NoteID      uint64    `gorm:"column:note_id;not null" json:"note_id"`
	Filename    string    `gorm:"column:filename;not null;comment:weixin:encode(url)" json:"filename"` // weixin:encode(url)
	OriginalURL string    `gorm:"column:original_url;not null" json:"original_url"`
	Width       int       `gorm:"column:width;not null" json:"width"`
	Height      int       `gorm:"column:height;not null" json:"height"`
	Sort        int       `gorm:"column:sort;not null" json:"sort"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName NoteImage's table name
func (*NoteImage) TableName() string {
	return TableNameNoteImage
}
