// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNoteContent = "note_content"

// NoteContent mapped from table <note_content>
type NoteContent struct {
	ID         uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NoteID     int64     `gorm:"column:note_id;not null" json:"note_id"`
	Text       string    `gorm:"column:text;not null" json:"text"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName NoteContent's table name
func (*NoteContent) TableName() string {
	return TableNameNoteContent
}
