// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNoteVideo = "note_video"

// NoteVideo mapped from table <note_video>
type NoteVideo struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID         uint64    `gorm:"column:uid;not null;comment:xxhash3" json:"uid"` // xxhash3
	NoteID      int64     `gorm:"column:note_id;not null" json:"note_id"`
	OriginalURL string    `gorm:"column:original_url;not null" json:"original_url"`
	Width       int       `gorm:"column:width;not null" json:"width"`
	Height      int       `gorm:"column:height;not null" json:"height"`
	CreateTime  time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName NoteVideo's table name
func (*NoteVideo) TableName() string {
	return TableNameNoteVideo
}
