// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePipeline = "pipeline"

// Pipeline mapped from table <pipeline>
type Pipeline struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NoteID       uint64    `gorm:"column:note_id;not null" json:"note_id"`
	IsCounted    bool      `gorm:"column:is_counted;not null;comment:交互量已采集" json:"is_counted"`       // 交互量已采集
	IsDetailed   bool      `gorm:"column:is_detailed;not null;comment:详情页已采集" json:"is_detailed"`     // 详情页已采集
	IsStructured bool      `gorm:"column:is_structured;not null;comment:内容已结构化" json:"is_structured"` // 内容已结构化
	IsEmbedded   bool      `gorm:"column:is_embedded;not null;comment:内容已向量化" json:"is_embedded"`     // 内容已向量化
	IsIndexed    bool      `gorm:"column:is_indexed;not null;comment:内容已入索引" json:"is_indexed"`       // 内容已入索引
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Pipeline's table name
func (*Pipeline) TableName() string {
	return TableNamePipeline
}
