// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWeixinRequest = "weixin_request"

// WeixinRequest mapped from table <weixin_request>
type WeixinRequest struct {
	ID         int       `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type       string    `gorm:"column:type;not null" json:"type"`
	UserID     string    `gorm:"column:user_id;not null;comment:wxuin或vid" json:"user_id"` // wxuin或vid
	Headers    string    `gorm:"column:headers;not null" json:"headers"`
	Cookie     string    `gorm:"column:cookie;not null" json:"cookie"`
	Status     string    `gorm:"column:status;not null" json:"status"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName WeixinRequest's table name
func (*WeixinRequest) TableName() string {
	return TableNameWeixinRequest
}
